version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calm-app
    restart: unless-stopped
    volumes:
      - ./:/app
      - app_data:/app/data
    environment:
      - FLASK_DEBUG=0
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - calm-network
    entrypoint: ["./docker-entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend-builder:
    image: node:16
    container_name: calm-frontend-builder
    working_dir: /app/frontend
    volumes:
      - ./:/app
    command: >
      bash -c "npm install && npm run build"
    networks:
      - calm-network

  nginx:
    image: nginx:1.21-alpine
    container_name: calm-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
      - frontend-builder
    networks:
      - calm-network

volumes:
  app_data:
    driver: local

networks:
  calm-network:
    driver: bridge 